# Gemfile for all Cucumber tests
source 'https://rubygems.org'

gem 'cucumber', '~> 2.4.0', '>= 2.4.0'
gem 'headless', '~> 2.3.1', '>= 2.3.1'
gem 'net', '~> 0.3.3', '>= 0.3.3'
gem 'selenium-webdriver', '~> 3.4.1', '>= 3.4.1'
gem 'watir', '~> 6.11.0', '>= 6.11.0'
